Imports Microsoft.VisualBasic

Public Class Helper
    Public Shared Sub PopulateStateDropDown(ByRef dropDown As DropDownList)
        With dropDown.Items
            .Clear()
            .Add("AL")
            .Add("AK")
            .Add("AR")
            .Add("AZ")
            .Add("CA")
            .Add("CO")
            .Add("CT")
            .Add("DC")
            .Add("DE")
            .Add("FL")
            .Add("GA")
            .Add("HI")
            .Add("IA")
            .Add("ID")
            .Add("IL")
            .Add("KS")
            .Add("KY")
            .Add("LA")
            .Add("MA")
            .Add("MD")
            .Add("ME")
            .Add("MI")
            .Add("MN")
            .Add("MO")
            .Add("MS")
            .Add("MT")
            .Add("NC")
            .Add("ND")
            .Add("NE")
            .Add("NH")
            .Add("NJ")
            .Add("NM")
            .Add("NV")
            .Add("NY")
            .Add("OH")
            .Add("OK")
            .Add("OR")
            .Add("PA")
            .Add("RI")
            .Add("SC")
            .Add("SD")
            .Add("TN")
            .Add("TX")
            .Add("UT")
            .Add("VA")
            .Add("VT")
            .Add("WA")
            .Add("WI")
            .Add("WV")
            .Add("WY")
        End With
    End Sub
End Class
